### ISSUE TITLE
安装包报错!

### ISSUE THREAD

**Issue by qwe159357890** [DWHengr/linyu-client#2]
![error](https://github.com/user-attachments/assets/0781dd88-6139-4fa7-a9e9-6c987962bb16)

**Comment by DWHengr** [comment]
win7系统，需要下载WebView2。我打包一个包含 WebView2 bootstrapper的，你在看一下是否可以在win7上运行。

**Comment by DWHengr** [comment]
https://github.com/DWHengr/linyu-client/releases/tag/linyu-v0.0.1 。更新了一个32位和64位的。
